
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ar.edu.unnoba.comp.jflextp;

/** CUP generated interface containing symbol constants. */
public interface MiParserSym {
  /* terminals */
  public static final int DISPLAY = 28;
  public static final int ENDDECLARE_SECTION = 38;
  public static final int WHEN = 17;
  public static final int STRING_LITERAL = 3;
  public static final int MULT = 44;
  public static final int ANY = 29;
  public static final int END_LOOP = 19;
  public static final int CIERRA_PARENTESIS = 53;
  public static final int ENTERO = 5;
  public static final int DIFERENTE = 51;
  public static final int DOS_PUNTOS = 57;
  public static final int ENTERO_LITERAL = 4;
  public static final int FLOAT_ARRAY_LITERAL = 11;
  public static final int CONTINUE = 20;
  public static final int ABRE_PARENTESIS = 52;
  public static final int MENOS_UNARIO = 46;
  public static final int INPUT_ARRAY = 34;
  public static final int IDENTIFICADOR = 2;
  public static final int NOT = 15;
  public static final int AND = 13;
  public static final int IGUAL = 40;
  public static final int FLOTANTE_LITERAL = 12;
  public static final int OR = 14;
  public static final int CIERRA_CORCHETE = 55;
  public static final int DIV = 45;
  public static final int LOOP = 16;
  public static final int ELSE_BACKWARD = 27;
  public static final int CONDITION = 22;
  public static final int BACKWARD_CONDITION = 23;
  public static final int EOF = 0;
  public static final int BOOLEAN = 8;
  public static final int INPUT_INT = 31;
  public static final int TRUE = 10;
  public static final int error = 1;
  public static final int COMA = 56;
  public static final int FLOAT_ARRAY = 7;
  public static final int MENOS = 43;
  public static final int INPUT_BOOL = 33;
  public static final int ABRE_CORCHETE = 54;
  public static final int MAYOR_QUE = 47;
  public static final int BREAK = 21;
  public static final int ELSE = 26;
  public static final int EQUIVALE = 41;
  public static final int MAYOR_IGUAL_QUE = 49;
  public static final int THEN = 24;
  public static final int PROGRAM_SECTION = 35;
  public static final int END = 25;
  public static final int INPUT_FLOAT = 32;
  public static final int ALL = 30;
  public static final int MENOR_QUE = 48;
  public static final int ENDPROGRAM_SECTION = 36;
  public static final int FALSE = 9;
  public static final int MENOR_IGUAL_QUE = 50;
  public static final int VALOR_MAS_CERCANO = 39;
  public static final int FLOTANTE = 6;
  public static final int DECLARE_SECTION = 37;
  public static final int MAS = 42;
  public static final int BACKWARD_LOOP = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "STRING_LITERAL",
  "ENTERO_LITERAL",
  "ENTERO",
  "FLOTANTE",
  "FLOAT_ARRAY",
  "BOOLEAN",
  "FALSE",
  "TRUE",
  "FLOAT_ARRAY_LITERAL",
  "FLOTANTE_LITERAL",
  "AND",
  "OR",
  "NOT",
  "LOOP",
  "WHEN",
  "BACKWARD_LOOP",
  "END_LOOP",
  "CONTINUE",
  "BREAK",
  "CONDITION",
  "BACKWARD_CONDITION",
  "THEN",
  "END",
  "ELSE",
  "ELSE_BACKWARD",
  "DISPLAY",
  "ANY",
  "ALL",
  "INPUT_INT",
  "INPUT_FLOAT",
  "INPUT_BOOL",
  "INPUT_ARRAY",
  "PROGRAM_SECTION",
  "ENDPROGRAM_SECTION",
  "DECLARE_SECTION",
  "ENDDECLARE_SECTION",
  "VALOR_MAS_CERCANO",
  "IGUAL",
  "EQUIVALE",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "MENOS_UNARIO",
  "MAYOR_QUE",
  "MENOR_QUE",
  "MAYOR_IGUAL_QUE",
  "MENOR_IGUAL_QUE",
  "DIFERENTE",
  "ABRE_PARENTESIS",
  "CIERRA_PARENTESIS",
  "ABRE_CORCHETE",
  "CIERRA_CORCHETE",
  "COMA",
  "DOS_PUNTOS"
  };
}

