
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ar.edu.unnoba.comp.compilertp;

/** CUP generated interface containing symbol constants. */
public interface MiParserSym {
  /* terminals */
  public static final int ENDDECLARE_SECTION = 38;
  public static final int SHOW = 32;
  public static final int STRING_LITERAL = 13;
  public static final int MULT = 5;
  public static final int INTEGER = 23;
  public static final int DOS_PUNTOS = 53;
  public static final int GREATER = 42;
  public static final int CONTINUE = 21;
  public static final int REPEAT = 19;
  public static final int OPPARENT = 47;
  public static final int CLPARENT = 48;
  public static final int LESS = 43;
  public static final int MINUS = 7;
  public static final int MENOS_UNARIO = 8;
  public static final int NOT = 18;
  public static final int AND = 16;
  public static final int OR = 17;
  public static final int CLBRACKETS = 50;
  public static final int DIV = 6;
  public static final int GEQ = 44;
  public static final int UNTIL = 20;
  public static final int DIFFERENT = 46;
  public static final int PLUS = 2;
  public static final int PUNTO_COMA = 51;
  public static final int ID = 9;
  public static final int EOF = 0;
  public static final int BOOLEAN = 22;
  public static final int DUPLE = 24;
  public static final int INPUT_INT = 33;
  public static final int TRUE = 15;
  public static final int error = 1;
  public static final int COMA = 52;
  public static final int INPUT_DUPLE = 36;
  public static final int OPBRACKETS = 49;
  public static final int INPUT_BOOL = 35;
  public static final int EQEQ = 4;
  public static final int BREAK = 27;
  public static final int PROMR = 41;
  public static final int EQ = 3;
  public static final int ELSE = 31;
  public static final int UNLESS = 29;
  public static final int FLOAT = 25;
  public static final int THEN = 28;
  public static final int LEQ = 45;
  public static final int PROGRAM_SECTION = 39;
  public static final int END = 30;
  public static final int INPUT_FLOAT = 34;
  public static final int STRING = 26;
  public static final int ENDPROGRAM_SECTION = 40;
  public static final int FLOAT_LITERAL = 12;
  public static final int FALSE = 14;
  public static final int DECLARE_SECTION = 37;
  public static final int DUPLA_LITERAL = 10;
  public static final int INTEGER_LITERAL = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "EQ",
  "EQEQ",
  "MULT",
  "DIV",
  "MINUS",
  "MENOS_UNARIO",
  "ID",
  "DUPLA_LITERAL",
  "INTEGER_LITERAL",
  "FLOAT_LITERAL",
  "STRING_LITERAL",
  "FALSE",
  "TRUE",
  "AND",
  "OR",
  "NOT",
  "REPEAT",
  "UNTIL",
  "CONTINUE",
  "BOOLEAN",
  "INTEGER",
  "DUPLE",
  "FLOAT",
  "STRING",
  "BREAK",
  "THEN",
  "UNLESS",
  "END",
  "ELSE",
  "SHOW",
  "INPUT_INT",
  "INPUT_FLOAT",
  "INPUT_BOOL",
  "INPUT_DUPLE",
  "DECLARE_SECTION",
  "ENDDECLARE_SECTION",
  "PROGRAM_SECTION",
  "ENDPROGRAM_SECTION",
  "PROMR",
  "GREATER",
  "LESS",
  "GEQ",
  "LEQ",
  "DIFFERENT",
  "OPPARENT",
  "CLPARENT",
  "OPBRACKETS",
  "CLBRACKETS",
  "PUNTO_COMA",
  "COMA",
  "DOS_PUNTOS"
  };
}

